app = 'semble-development'
primary_region = 'yyz'

[build]

[processes]
  web = "npm start"
  feed-worker = "npm run worker:feeds"
  search-worker = "npm run worker:search"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[vm]]
  processes = ['feed-worker']
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[[vm]]
  processes = ['search-worker']
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
NODE_ENV="dev"
BASE_URL="https://api.dev.semble.so"
HOST="0.0.0.0"
APP_URL="https://dev.semble.so"
ACCESS_TOKEN_EXPIRES_IN=300
REFRESH_TOKEN_EXPIRES_IN=2592000